files:
  exclude:
    - '**/bindata.go'
    - 'vendor/**/*'
    - 'Gopkg.lock'
targets:
  - patterns: ['**/*']
    rules:
      linebreak:
        enforce: true
        style: lf
      final-newline:
        enforce: true
        num: 1
      first-newline:
        enforce: true
        num: 0
      no-bom:
        enforce: true
      no-eol-space:
        enforce: true
  - patterns: ['**/*.md']
    rules:
      no-eol-space:
        enforce: false
