files:
  include:
    - './**/*'
  exclude:
    - '.git/**/*'

targets:
  default:
    rules:
      indent:
        enforce: false
        size: 2
        style: soft
      linebreak:
        enforce: true
        style: lf
      first-newline:
        enforce: true
        num: 0
      final-newline:
        enforce: true
        num: 1
      no-bom:
        enforce: true
      no-eol-space:
        enforce: true
